# Generated by Django 5.2.4 on 2025-08-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
