# Generated by Django 5.2.4 on 2025-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_claim_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='claim_attachments/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
