# Generated by Django 5.2.4 on 2025-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_claim_attachment_claim_location_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov', models.CharField(max_length=100, verbose_name='Gouvernorat')),
                ('deleg', models.CharField(max_length=100, verbose_name='Délégation')),
                ('cite', models.CharField(max_length=100, verbose_name='Cité')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Code Postal')),
            ],
            options={
                'verbose_name': 'Code Postal',
                'verbose_name_plural': 'Codes Postaux',
            },
        ),
    ]
