# Generated by Django 5.2.4 on 2025-08-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
