# Generated by Django 5.2.4 on 2025-08-06 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='image',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.claimtype'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
