# Generated by Django 5.2.5 on 2025-08-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_municipality_delegation_municipality_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.claimtype'),
        ),
        migrations.AlterField(
            model_name='claimtype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
