# Generated by Django 5.2.5 on 2025-08-08 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_claim_claim_type_alter_claimtype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claimtype'),
        ),
    ]
