# Generated by Django 5.2.4 on 2025-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_municipality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='postal_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
